config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins, path: '/', path_names: {
    sign_in: 'login',
    sign_out: 'logout'
  }, controllers: { sessions: 'sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post ':store_id/webhook', to: 'webhooks#webhook', as: 'webhooks'

  root to: 'home#index'

  namespace :admin do
    get '/', to: 'dashboard#index', as: :dashboard
    resources :orders, only: [:index] do
      get 'data', on: :collection,
                  action: :table_data, defaults: { format: 'json' }
    end
    resources :products, only: %i[index show] do
      get 'data', on: :collection,
                  action: :table_data, defaults: { format: 'json' }
      resources :variants, only: %i[show] do
        get 'data', on: :collection,
                    action: :table_data, defaults: { format: 'json' }
      end
    end
    get 'inventory', to: 'inventory#index', as: :inventory
    get 'inventory_data', to: 'inventory#table_data', as: :inventory_data
  end
end

app/controllers/admin/inventory_controller.rb
# frozen_string_literal: true

# Admin Inventory Dashboard Controller
class Admin::InventoryController < AdminController
  def index
    @subheader = @title = 'Inventory'
  end

  def table_data
    respond_to do |format|
      format.json do
        render json: InventoryDatatable.new(params,
                                            view_context: view_context)
      end
    end
  end
end

app/views/admin/inventory/index.html.erb
<div class="kt-content kt-grid__item kt-grid__item--fluid" id="kt_content">
  <div class="kt-portlet kt-portlet--mobile">
    <div class="kt-portlet__head">
      <div class="kt-portlet__head-label">
        <h3 class="kt-portlet__head-title">
          Inventory 
        </h3>
      </div>
    </div>
    <div class="kt-portlet__body">
      <form class="kt-form kt-form--fit kt-margin-b-20">
        <div class="row kt-margin-b-20">
          <div class="col-lg-4 kt-margin-b-10-tablet-and-mobile">
            <label>Product Title:</label>
            <input type="text" class="form-control kt-input" placeholder="Title - E.g: Bear Phone Case" data-col-index="0">
          </div>
          <div class="col-lg-4 kt-margin-b-10-tablet-and-mobile">
            <label>Product Type:</label>
            <select class="form-control kt-input" id="type_select" data-col-index="1">
              <option value="">Any</option>
              <% SharedProduct.order('product_type').pluck(:product_type).uniq.each do |product_type| %>
                <option value="<%= product_type %>"><%= product_type %></option>
              <% end %>
            </select>
          </div>
          <div class="col-lg-4 kt-margin-b-10-tablet-and-mobile">
            <label>Product Vendor:</label>
            <select class="form-control kt-input" id="vendor_select"  data-col-index="2">
              <option value="">Any</option>
              <% SharedProduct.order('vendor').pluck(:vendor).uniq.each do |vendor| %>
                <option value="<%= vendor %>"><%= vendor %></option>
              <% end %>
            </select>
          </div>
        </div>
        <div class="row kt-margin-b-20">
          <div class="col-lg-3 kt-margin-b-10-tablet-and-mobile">
            <label>Variant Title:</label>
            <input type="text" class="form-control kt-input" placeholder="Title - E.g: Bear Phone Case" data-col-index="3">
          </div>
          <div class="col-lg-3 kt-margin-b-10-tablet-and-mobile">
            <label>Variant SKU:</label>
            <input type="text" class="form-control kt-input" placeholder="SKU - E.g: PHONE-BEAR-1092" data-col-index="4">
          </div>
          <div class="col-lg-2 kt-margin-b-10-tablet-and-mobile">
            <label>Variant Quantity:</label>
            <select class="form-control kt-input" id="count_query_type">
              <option value="">Any</option>
              <option value="eq">Equal</option>
              <option value="lt">Less Than</option>
              <option value="gt">Greater Than</option>
            </select>
          </div>
          <div class="col-lg-1 kt-margin-b-10-tablet-and-mobile">
            <label>&nbsp;</label>
            <input type="number" class="form-control" id="count_query_number" placeholder="E.g: 7">
            <input type="hidden" class="kt-input" id="query_string" data-col-index="5">
          </div>
          <div class="col-lg-3 kt-margin-b-10-tablet-and-mobile">
            <label>Variant Options:</label>
            <input type="text" class="form-control kt-input" placeholder="Variant Options - E.g: XXL" data-col-index="6">
          </div>
        </div>
        <div class="row kt-margin-b-20">
        </div>
        <div class="kt-separator kt-separator--md kt-separator--dashed"></div>
        <div class="row">
          <div class="col-lg-12">
            <button class="btn btn-brand kt-btn kt-btn--icon" id="m_search">
              <span> <i class="la la-search"></i> <span>Search</span> </span>
            </button>
            &nbsp;&nbsp; 
            <button class="btn btn-secondary kt-btn kt-btn--icon" id="m_reset">
              <span> <i class="la la-close"></i> <span>Reset</span> </span>
            </button>
          </div>
        </div>
        <div class="kt-separator kt-separator--md kt-separator--dashed"></div>
      </form>
      <table class="table table-striped- table-bordered table-hover" id="inventory_datatable" data-source="<%= admin_inventory_data_path %>">
        <thead>
          <tr>
            <th>Product Title</th>
            <th>Type</th>
            <th>Vendor</th>
            <th>Variant Title</th>
            <th>SKU</th>
            <th>Quantity</th>
            <th>Options</th>
          </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
    </div>
  </div>
</div>