config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins, path: '/', path_names: {
    sign_in: 'login',
    sign_out: 'logout'
  }, controllers: { sessions: 'sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post ':store_id/webhook', to: 'webhooks#webhook', as: 'webhooks'

  root to: 'home#index'

  namespace :admin do
    get '/', to: 'dashboard#index', as: :dashboard
    resources :orders, only: [:index] do
      get 'data', on: :collection,
                  action: :table_data, defaults: { format: 'json' }
    end
    resources :products, only: %i[index show] do
      get 'data', on: :collection,
                  action: :table_data, defaults: { format: 'json' }
      resources :variants, only: %i[show] do
        get 'data', on: :collection,
                    action: :table_data, defaults: { format: 'json' }
      end
    end
    get 'inventory', to: 'inventory#index', as: :inventory
    get 'inventory_data', to: 'inventory#table_data', as: :inventory_data
  end
end

app/models/order.rb
# frozen_string_literal: true

# == Schema Information
# Schema version: 20190408142208
#
# Table name: orders
#
#  id                 :bigint(8)        not null, primary key
#  cancelled_at       :datetime
#  closed_at          :datetime
#  financial_status   :string
#  fulfillment_status :string
#  name               :string           indexed
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  store_id           :bigint(8)        indexed
#

# Represents a Shopify Order.
class Order < ApplicationRecord
  has_many :line_items, dependent: :delete_all
  has_many :product_variants, through: :line_items
  belongs_to :store
  before_save :populate_blank_fulfillment_status

  def self.sync!(shopify_order, store_id)
    order = find_by_id(shopify_order.attributes[:id])
    order ||= new(store_id: store_id)
    order.merge_with(shopify_order)
    order.save!
    sync_line_items(shopify_order, store_id)
    order
  end

  def self.sync_line_items(shopify_order, store_id)
    shopify_order.line_items.each do |s_l_i|
      LineItem.sync!(s_l_i, store_id, shopify_order.attributes[:id])
    end
  end

  def human_financial_status
    financial_status.humanize
  end

  def human_fulfillment_status
    fulfillment_status.humanize
  end

  def populate_blank_fulfillment_status
    self.fulfillment_status = 'unfulfilled' if fulfillment_status.blank?
    true
  end
end

app/controllers/admin/orders_controller.rb
# frozen_string_literal: true

# Admin Orders Dashboard Controller
class Admin::OrdersController < AdminController
  def index
    @title = 'Orders'
    @subheader = 'Orders Dashboard'
  end

  def table_data
    respond_to do |format|
      format.json do
        render json: OrdersDatatable.new(params,
                                         view_context: view_context)
      end
    end
  end
end

app/views/admin/orders/index.html.erb
<div class="kt-content kt-grid__item kt-grid__item--fluid" id="kt_content">
  <div class="kt-portlet kt-portlet--mobile">
    <div class="kt-portlet__head">
      <div class="kt-portlet__head-label">
        <h3 class="kt-portlet__head-title">
          All Orders 
        </h3>
      </div>
    </div>
    <div class="kt-portlet__body">
      <form class="kt-form kt-form--fit kt-margin-b-20">
        <div class="row kt-margin-b-20">
          <div class="col-lg-2 kt-margin-b-10-tablet-and-mobile">
            <label>Store:</label>
            <select class="form-control kt-input" data-col-index="0">
              <option value="">Any</option>
            </select>
          </div>
          <div class="col-lg-2 kt-margin-b-10-tablet-and-mobile">
            <label>Order#:</label>
            <input type="text" class="form-control kt-input" placeholder="E.g: #21238" data-col-index="1">
          </div>
          <div class="col-lg-3 kt-margin-b-10-tablet-and-mobile">
            <label>Order Placed At:</label>
            <div class="input-daterange input-group" id="m_datepicker">
              <input type="text" class="form-control kt-input" name="start" placeholder="From" data-col-index="2"/>
              <div class="input-group-append">
                <span class="input-group-text"><i class="la la-ellipsis-h"></i></span>
              </div>
              <input type="text" class="form-control kt-input" name="end" placeholder="To" data-col-index="5"/>
            </div>
          </div>
          <div class="col-lg-2 kt-margin-b-10-tablet-and-mobile">
            <label>Order Financial Status:</label>
            <select class="form-control kt-input" data-col-index="3">
              <option value="">Any</option>
            </select>
          </div>
          <div class="col-lg-2 kt-margin-b-10-tablet-and-mobile">
            <label>Order Fulfillment Status:</label>
            <select class="form-control kt-input" data-col-index="4">
              <option value="">Any</option>
            </select>
          </div>
        </div>
        <div class="row kt-margin-b-20">
        </div>
        <div class="row">
          <div class="col-lg-2 kt-margin-b-10-tablet-and-mobile">
            <label>Item Details:</label>
            <input type="text" class="form-control kt-input" id="variant_title_input" placeholder="Title - E.g: Bear Phone Case" data-col-index="5">
          </div>
          <div class="col-lg-2 kt-margin-b-10-tablet-and-mobile">
            <label>Product Details:</label>
            <input type="text" class="form-control kt-input" id="variant_title_input" placeholder="Title - E.g: Bear Phone Case" data-col-index="6">
          </div>

          <div class="col-lg-2 kt-margin-b-10-tablet-and-mobile">
            <label>SKU:</label>
            <input type="text" class="form-control kt-input" placeholder="SKU - E.g: PHONE-BEAR-1092" data-col-index="7">
          </div>
          <div class="col-lg-2 kt-margin-b-10-tablet-and-mobile">
            <label>Quantity:</label>
            <select class="form-control kt-input" id="count_query_type">
              <option value="">Any</option>
              <option value="eq">Equal</option>
              <option value="lt">Less Than</option>
              <option value="gt">Greater Than</option>
            </select>
          </div>
          <div class="col-lg-1 kt-margin-b-10-tablet-and-mobile">
            <label>&nbsp;</label>
            <input type="number" class="form-control" id="count_query_number" placeholder="E.g: 7">
            <input type="hidden" class="kt-input" id="query_string" data-col-index="8">
          </div>
          <div class="col-lg-2 kt-margin-b-10-tablet-and-mobile">
            <label>Item Fulfillment Status:</label>
            <select class="form-control kt-input" data-col-index="9">
              <option value="">Any</option>
            </select>
          </div>
        </div>
        <div class="row kt-margin-b-20">
        </div>
        <div class="kt-separator kt-separator--md kt-separator--dashed"></div>
        <div class="row">
          <div class="col-lg-12">
            <button class="btn btn-brand kt-btn kt-btn--icon" id="m_search">
              <span> <i class="la la-search"></i> <span>Search</span> </span>
            </button>
            &nbsp;&nbsp; 
            <button class="btn btn-secondary kt-btn kt-btn--icon" id="m_reset">
              <span> <i class="la la-close"></i> <span>Reset</span> </span>
            </button>
          </div>
        </div>
        <div class="kt-separator kt-separator--md kt-separator--dashed"></div>
      </form>
      <table class="table table-striped- table-bordered table-hover" id="orders_datatable" data-source="<%= data_admin_orders_path %>">
        <thead>
          <tr>
            <th>Store</th>
            <th>Order #</th>
            <th>Date</th>
            <th>Financial Status</th>
            <th>Fulfillment Status</th>
            <th>Item</th>
            <th>Product Details</th>
            <th>SKU</th>
            <th>Quantity</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
      <!--end: Datatable -->
    </div>
  </div>
</div>