config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins, path: '/', path_names: {
    sign_in: 'login',
    sign_out: 'logout'
  }, controllers: { sessions: 'sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post ':store_id/webhook', to: 'webhooks#webhook', as: 'webhooks'

  root to: 'home#index'

  namespace :admin do
    get '/', to: 'dashboard#index', as: :dashboard
    resources :orders, only: [:index] do
      get 'data', on: :collection,
                  action: :table_data, defaults: { format: 'json' }
    end
    resources :products, only: %i[index show] do
      get 'data', on: :collection,
                  action: :table_data, defaults: { format: 'json' }
      resources :variants, only: %i[show] do
        get 'data', on: :collection,
                    action: :table_data, defaults: { format: 'json' }
      end
    end
    get 'inventory', to: 'inventory#index', as: :inventory
    get 'inventory_data', to: 'inventory#table_data', as: :inventory_data
  end
end

app/models/product.rb
# frozen_string_literal: true

# == Schema Information
# Schema version: 20190327113822
#
# Table name: products
#
#  id                :bigint(8)        not null, primary key
#  title             :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  shared_product_id :bigint(8)        indexed
#  store_id          :bigint(8)        indexed
#

# Represents a Shopify Product.
class Product < ApplicationRecord
  has_many :variants, class_name: 'ProductVariant', dependent: :destroy
  has_many :line_items
  belongs_to :shared_product, optional: true
  belongs_to :store

  after_destroy :destroy_shared_attributes, if: :last_product?

  def self.sync!(shopify_product, store_id)
    product = find_by_id(shopify_product.attributes[:id])
    product ||= new(store_id: store_id)
    product.merge_with(shopify_product)
    product.save!
    variants = sync_variants(shopify_product, store_id)
    sync_shared_attributes(shopify_product, variants, product)
    product
  end

  def destroy_shared_attributes
    shared_product.destroy
  end

  def last_product?
    shared_product.products.count.zero?
  end

  def self.sync_shared_attributes(shopify_product, variants, product)
    shared_product = SharedProduct.sync!(shopify_product)
    ProductVariant.where(id: variants.map(&:id))
                  .update_all(shared_product_id: shared_product.id)
    SharedProductVariant.where(
      id: variants.map(&:shared_product_variant_id)
    ).update_all(shared_product_id: shared_product.id)
    product.update_attribute(:shared_product_id, shared_product.id)
  end

  def self.sync_variants(shopify_product, store_id)
    shopify_product.variants.map do |s_v|
      images = shopify_product.images
      image = images.find { |x| x.attributes[:id] == s_v.image_id }
      image_url = image.try(:attributes).try(:[], :src)
      ProductVariant.sync!(s_v, store_id, image_url,
                           shopify_product.attributes[:id])
    end
  end
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

# Admin Products Dashboard Controller
class Admin::ProductsController < AdminController
  def index
    @title = 'Products'
    @subheader = 'Products Dashboard'
  end

  def show
    @product = SharedProduct.find(params[:id])
    @title = @subheader = @product.title
    @stores_count = @product.products.count
  end

  def table_data
    respond_to do |format|
      format.json do
        render json: ProductsDatatable.new(params,
                                           view_context: view_context)
      end
    end
  end
end

app/views/admin/products/index.html.erb
<div class="kt-content kt-grid__item kt-grid__item--fluid" id="kt_content">
  <div class="kt-portlet kt-portlet--mobile">
    <div class="kt-portlet__head">
      <div class="kt-portlet__head-label">
        <h3 class="kt-portlet__head-title">
          All Products 
        </h3>
      </div>
    </div>
    <div class="kt-portlet__body">
      <form class="kt-form kt-form--fit kt-margin-b-20">
        <div class="row kt-margin-b-20">
          <div class="col-lg-3 kt-margin-b-10-tablet-and-mobile">
            <label>Product Title:</label>
            <input type="text" class="form-control kt-input" placeholder="Title - E.g: Bear Phone Case" data-col-index="0">
          </div>
          <div class="col-lg-2 kt-margin-b-10-tablet-and-mobile">
            <label>Variants Count:</label>
            <select class="form-control kt-input" id="count_query_type">
              <option value="">Any</option>
              <option value="eq">Equal</option>
              <option value="lt">Less Than</option>
              <option value="gt">Greater Than</option>
            </select>
          </div>
          <div class="col-lg-2 kt-margin-b-10-tablet-and-mobile">
            <label>&nbsp;</label>
            <input type="number" class="form-control" id="count_query_number" placeholder="Number - E.g: 7">
            <input type="hidden" class="kt-input" id="query_string" data-col-index="1">
          </div>
        </div>
        <div class="row kt-margin-b-20">
          <div class="col-lg-3 kt-margin-b-10-tablet-and-mobile">
            <label>Type:</label>
            <select class="form-control kt-input" id="type_select" data-col-index="2">
              <option value="">Any</option>
              <% SharedProduct.order('product_type').pluck(:product_type).uniq.each do |product_type| %>
                <option value="<%= product_type %>"><%= product_type %></option>
              <% end %>
            </select>
          </div>
          <div class="col-lg-4 kt-margin-b-10-tablet-and-mobile">
            <label>Vendor:</label>
            <select class="form-control kt-input" id="vendor_select"  data-col-index="3">
              <option value="">Any</option>
              <% SharedProduct.order('vendor').pluck(:vendor).uniq.each do |vendor| %>
                <option value="<%= vendor %>"><%= vendor %></option>
              <% end %>
            </select>
          </div>
        </div>
        <div class="kt-separator kt-separator--md kt-separator--dashed"></div>
        <div class="row">
          <div class="col-lg-12">
            <button class="btn btn-brand kt-btn kt-btn--icon" id="m_search">
              <span> <i class="la la-search"></i> <span>Search</span> </span>
            </button>
            &nbsp;&nbsp; 
            <button class="btn btn-secondary kt-btn kt-btn--icon" id="m_reset">
              <span> <i class="la la-close"></i> <span>Reset</span> </span>
            </button>
          </div>
        </div>
        <div class="kt-separator kt-separator--md kt-separator--dashed"></div>
      </form>
      <table class="table table-striped- table-bordered table-hover" id="products_datatable" data-source="<%= data_admin_products_path %>">
        <thead>
          <tr>
            <th>Product</th>
            <th>Variants</th>
            <th>Type</th>
            <th>Vendor</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/products/show.html.erb
<div class="kt-content kt-grid__item kt-grid__item--fluid" id="kt_content">
  <div class="row" data-sticky-container>
    <div class="col-lg-4">
      <div class="kt-portlet kt-portlet--contain">
        <div class="kt-blog-grid">
          <div class="kt-blog-grid__head">
            <a class="kt-blog-grid__thumb-link">
              <%= image_tag((@product.image_url || 'admin/placeholder.png'), class: "kt-blog-grid__image") %>
            </a>
          </div>
          <div class="kt-portlet__body">
            <div class="kt-blog-grid__body">
                <h4 class="kt-blog-grid__title">
                    Product Details
                </h4>
                <div class="kt-blog-grid__content">
                  <ul>
                    <li>
                      Title: <b> <%= @product.title %> </b>
                    </li>
                    <li>
                      Product Type: <b> <%= @product.product_type %> </b>
                    </li>
                    <li>
                      Vendor: <b> <%= @product.vendor %> </b>
                    </li>
                  </ul>
                </div>
                <div class="accordion accordion-outline" id="accordionExample4">
                  <div class="card">
                    <div class="card-header" id="headingOne4">
                      <div class="card-title collapsed" data-toggle="collapse" data-target="#collapseOne4" aria-expanded="false" aria-controls="collapseOne4"> <i class="la la-external-link"></i>View in <%= @stores_count %> Shopify <%= "Store".pluralize(@stores_count) %></div>
                    </div>
                    <div id="collapseOne4" class="card-body-wrapper collapse" aria-labelledby="headingOne" data-parent="#accordionExample4">
                      <div class="card-body">
                        <% @product.products.includes(:store).each do |p_i| %>
                          <a href='<%="https://#{p_i.store.url}products/#{p_i.id}"%>' target="_blank "> <%= p_i.store.title %> Store </a>
                          <br>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-8">
      <div class="kt-portlet kt-portlet--contain">
        <div class="kt-blog-grid">
          <div class="kt-portlet__body">
            <div class="kt-blog-grid__body">
              <h4 class="kt-blog-grid__title">
                  Variants
              </h4>
              <div class="kt-content kt-grid__item kt-grid__item--fluid">
               <table class="table table-striped- table-bordered table-hover" id="product_variants_datatable" data-source="<%= data_admin_product_variants_path(product_id: @product.id) %>">
                 <thead>
                   <tr>
                     <th>Title</th>
                     <th>SKU</th>
                     <th>Inventory Quantity</th>
                     <th>Options</th>
                   </tr>
                 </thead>
                 <tbody>
                 </tbody>
               </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>