config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins, path: '/', path_names: {
    sign_in: 'login',
    sign_out: 'logout'
  }, controllers: { sessions: 'sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post ':store_id/webhook', to: 'webhooks#webhook', as: 'webhooks'

  root to: 'home#index'

  namespace :admin do
    get '/', to: 'dashboard#index', as: :dashboard
    resources :orders, only: [:index] do
      get 'data', on: :collection,
                  action: :table_data, defaults: { format: 'json' }
    end
    resources :products, only: %i[index show] do
      get 'data', on: :collection,
                  action: :table_data, defaults: { format: 'json' }
      resources :variants, only: %i[show] do
        get 'data', on: :collection,
                    action: :table_data, defaults: { format: 'json' }
      end
    end
    get 'inventory', to: 'inventory#index', as: :inventory
    get 'inventory_data', to: 'inventory#table_data', as: :inventory_data
  end
end

app/views/layouts/_aside.html.erb
<button class="kt-aside-close " id="kt_aside_close_btn"><i class="la la-close"></i></button>
<div class="kt-aside kt-aside--fixed kt-grid__item kt-grid kt-grid--desktop kt-grid--hor-desktop" id="kt_aside">
  <div class="kt-aside__brand kt-grid__item " id="kt_aside_brand">
    <div class="kt-aside__brand-logo">
      <%= link_to(image_tag('admin/logo_no_text.jpg', size: '70x70'), admin_dashboard_path )%>
    </div>
    <div class="kt-aside__brand-tools">
      <button class="kt-aside__brand-aside-toggler kt-aside__brand-aside-toggler--left" id="kt_aside_toggler"><span></span></button>
    </div>
  </div>
  <div class="kt-aside-menu-wrapper kt-grid__item kt-grid__item--fluid" id="kt_aside_menu_wrapper">
    <div id="kt_aside_menu" class="kt-aside-menu " data-ktmenu-vertical="1" data-ktmenu-scroll="1" data-ktmenu-dropdown-timeout="500" >
      <ul class="kt-menu__nav ">
        <li class="kt-menu__item <%= active_item_class(:dashboard, :index) %>" aria-haspopup="true" data-ktmenu-submenu-toggle="hover">
          <a href="<%= admin_dashboard_path %>" class="kt-menu__link"><i class="kt-menu__link-icon flaticon2-poll-symbol"></i><span class="kt-menu__link-text">Main Dashboard</span></a>
        </li>

        <li class="kt-menu__item kt-menu__item--submenu <%= active_item_class(:orders, :index) %> <%= open_menu_class(:orders) %>" aria-haspopup="true" data-ktmenu-submenu-toggle="hover">
          <a href="javascript:;" class="kt-menu__link kt-menu__toggle"><i class="kt-menu__link-icon flaticon2-paperplane"></i><span class="kt-menu__link-text">Orders</span><i class="kt-menu__ver-arrow la la-angle-right"></i></a>
          <div class="kt-menu__submenu ">
            <span class="kt-menu__arrow"></span>
            <ul class="kt-menu__subnav">
              <li class="kt-menu__item kt-menu__item--parent" aria-haspopup="true" >
                <span class="kt-menu__link"><span class="kt-menu__link-text">Orders</span></span>
              </li>
              <li class="kt-menu__item <%= active_item_class(:orders, :index) %>" aria-haspopup="true" >
                <a href="<%= admin_orders_path %>" class="kt-menu__link">
                  <i class="kt-menu__link-icon flaticon2-list"><span></span></i>
                  <span class="kt-menu__link-text">All Orders</span>
                </a>
              </li>
            </ul>
          </div>
        </li>

        <li class="kt-menu__item kt-menu__item--submenu <%= active_item_class(:products, :index) %> <%= open_menu_class(:products) || open_menu_class(:inventory) %>" aria-haspopup="true" data-ktmenu-submenu-toggle="hover">
          <a href="javascript:;" class="kt-menu__link kt-menu__toggle"><i class="kt-menu__link-icon flaticon-price-tag"></i><span class="kt-menu__link-text">Products</span><i class="kt-menu__ver-arrow la la-angle-right"></i></a>
          <div class="kt-menu__submenu ">
            <span class="kt-menu__arrow"></span>
            <ul class="kt-menu__subnav">
              <li class="kt-menu__item kt-menu__item--parent" aria-haspopup="true" >
                <span class="kt-menu__link"><span class="kt-menu__link-text">Products</span></span>
              </li>
              <li class="kt-menu__item <%= active_item_class(:products, :index) %>" aria-haspopup="true" >
                <a href="<%= admin_products_path %>" class="kt-menu__link">
                  <i class="kt-menu__link-icon flaticon2-list"><span></span></i>
                  <span class="kt-menu__link-text">All Products</span>
                </a>
              </li>
              <li class="kt-menu__item <%= active_item_class(:inventory, :index) %>" aria-haspopup="true" >
                <a href="<%= admin_inventory_path %>" class="kt-menu__link">
                  <i class="kt-menu__link-icon flaticon2-shelter"><span></span></i>
                  <span class="kt-menu__link-text">Inventory</span>
                </a>
              </li>
            </ul>
          </div>
        </li>

     </ul>
    </div>
  </div>
  <div class="kt-aside__footer kt-grid__item" id="kt_aside_footer">
    <div class="kt-aside__footer-nav">
    </div>
  </div>
</div>

app/views/layouts/_empty_subheader.html.erb
<div class="kt-subheader kt-grid__item" id="kt_subheader">
  <div class="kt-subheader__main">
    <h3 class="kt-subheader__title">
    </h3>
  </div>
  <div class="kt-subheader__toolbar">
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<% {
  notice: :success,
  alert: :danger,
  error: :danger,
  success: :success,
  warning: :warning,
  info: :info
}.each do |flash_type, div_class|%>
  <% if flash[flash_type] %>
    <div class="alert alert-<%= div_class%> fade show" role="alert">
      <div class="alert-text"><%= flash[flash_type] %></div>
    </div>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<div class="kt-footer kt-grid__item kt-grid kt-grid--desktop kt-grid--ver-desktop">
    <div class="kt-footer__copyright">2019&nbsp;&copy;&nbsp;Horse</div>
</div>

app/views/layouts/_header.html.erb
<div id="kt_header" class="kt-header kt-grid__item kt-header--fixed " >
  <!-- begin:: Header Menu -->
  <button class="kt-header-menu-wrapper-close" id="kt_header_menu_mobile_close_btn"><i class="la la-close"></i></button>
  <div class="kt-header-menu-wrapper" id="kt_header_menu_wrapper">
    <div id="kt_header_menu" class="kt-header-menu kt-header-menu-mobile kt-header-menu--layout- " >
    </div>
  </div>
  <!-- end:: Header Menu -->
  <!-- begin:: Header Topbar -->
  <div class="kt-header__topbar">
    <!--begin: User Bar -->
    <div class="kt-header__topbar-item kt-header__topbar-item--user">
      <div class="kt-header__topbar-wrapper" data-toggle="dropdown" data-offset="0px, 0px">
        <div class="kt-header__topbar-user">
          <span class="kt-header__topbar-welcome kt-hidden-mobile">Hello,</span> <span class="kt-header__topbar-username kt-hidden-mobile"><%= current_admin.full_name %></span>
          <span class="kt-badge kt-badge--username kt-badge--lg kt-badge--brand kt-badge--bold"><%= current_admin.full_name[0] %></span> 
        </div>
      </div>
      <div class="dropdown-menu dropdown-menu-fit dropdown-menu-right dropdown-menu-anim dropdown-menu-top-unround dropdown-menu-sm">
        <ul class="kt-nav kt-margin-b-10">
          <li class="kt-nav__item">
           <a href="#" class="kt-nav__link">
            <span class="kt-nav__link-icon"><i class="flaticon2-calendar-3"></i></span>
            <span class="kt-nav__link-text">My Profile</span>
           </a>
          </li>
          <li class="kt-nav__item">
           <a href="#" class="kt-nav__link">
            <span class="kt-nav__link-icon"><i class="flaticon2-gear"></i></span>
            <span class="kt-nav__link-text">Settings</span>
           </a>
          </li>
          <li class="kt-nav__item kt-nav__item--custom kt-margin-t-15">
            <%= link_to("Sign Out", destroy_admin_session_path, method: :delete, class: "btn btn-outline-metal btn-hover-brand btn-upper btn-font-dark btn-sm btn-bold") %>
        </ul>
      </div>
    </div>
    <!--end: User Bar -->
  </div>
  <!-- end:: Header Topbar -->
</div>

app/views/layouts/_header_mobile.html.erb
<div id="kt_header_mobile" class="kt-header-mobile kt-header-mobile--fixed " >
  <div class="kt-header-mobile__logo">
    <%= link_to(image_tag('admin/logo_no_text.jpg', size: '50x50'), admin_dashboard_path )%>
  </div>
  <div class="kt-header-mobile__toolbar">
    <button class="kt-header-mobile__toolbar-toggler kt-header-mobile__toolbar-toggler--left" id="kt_aside_mobile_toggler"><span></span></button>
    <button class="kt-header-mobile__toolbar-topbar-toggler" id="kt_header_mobile_topbar_toggler"><i class="flaticon-more"></i></button>
  </div>
</div>

app/views/layouts/_subheader.html.erb
<div class="kt-subheader kt-grid__item" id="kt_subheader">
  <div class="kt-subheader__main">
    <h3 class="kt-subheader__title">
      <%= @subheader %>
    </h3>
    <% case params[:controller] %>
    <% when 'admin/products' %>
      <% if params[:action] == "show" %>
        <span class="kt-subheader__separator kt-subheader__separator--v"></span> 
        <div class="kt-subheader__breadcrumbs">
          <%= link_to("All Products", admin_products_path, class: "kt-subheader__breadcrumbs-link") %>
        </div>
      <% end %>
    <% when 'admin/variants' %>
      <% if params[:action] == "show" %>
        <span class="kt-subheader__separator kt-subheader__separator--v"></span> 
        <div class="kt-subheader__breadcrumbs">
          <%= link_to(@variant.shared_product.title, admin_product_path(@variant.shared_product_id), class: "kt-subheader__breadcrumbs-link") %>
          <span class="kt-subheader__breadcrumbs-separator"></span>
          <%= link_to("All Products", admin_products_path, class: "kt-subheader__breadcrumbs-link") %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="kt-subheader__toolbar">
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Horse <%= page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"></script>
    <script>
        WebFont.load({

            google: {
"families":[
"Poppins:300,400,500,600,700"]},

            active: function() {

                sessionStorage.fonts = true;
            }
        });
    </script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% unless current_admin %>
      <%= stylesheet_link_tag    'keen/login', media: 'all', 'data-turbolinks-track': 'reload' %>
    <% end %>
    <%= javascript_include_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Latest updates and statistic charts">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta charset="utf-8"/>
    <%= favicon_link_tag asset_path('admin/favicon.png') %>

  </head>
  <% if current_admin %>
    <body class="kt-header--fixed kt-header-mobile--fixed kt-subheader--enabled kt-subheader--transparent kt-aside--enabled kt-aside--fixed kt-page--loading">
      <%= render 'layouts/header_mobile' %>
      <!-- begin:: Root -->
      <div class="kt-grid kt-grid--hor kt-grid--root">
        <!-- begin:: Page -->
        <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--ver kt-page">
          <%= render 'layouts/aside' %>
          <div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor kt-wrapper" id="kt_wrapper">
            <%= render 'layouts/header' %>
              <%= render 'layouts/subheader' %>
            <%= render 'layouts/flash_messages' %>
            <%= yield %>
            <%= render 'layouts/footer' %>
          </div>
        </div>
      </div>
    </body>
  <% else %>
    <%= yield %>
  <% end %>

</html>